;;; Generated by scripts/build-editor-support.js
;;; Keep in sync with shared/syntax-matrix.json

(comment) @comment
(line_comment) @comment
(block_comment) @comment
(string_literal) @string
(char_literal) @string.special
(int_literal) @number
(float_literal) @number.float

(identifier) @variable
(function_declaration name: (identifier) @function)
(call_expression function: (identifier) @function.call)
(type_identifier) @type

[
  "if"
  "else"
  "for"
  "while"
  "match"
  "break"
  "continue"
  "auto"
  "func"
  "returns"
  "return"
  "const"
  "class"
  "interface"
  "enum"
  "import"
  "common"
  "is"
  "as"
  "in"
] @keyword

[
  "true"
  "false"
  "none"
] @constant.builtin

[
  "string"
  "bool"
  "void"
  "int"
  "float"
  "char"
  "optional"
  "result"
  "list"
  "map"
  "tuple"
  "set"
  "range"
  "Stringable"
  "Hashable"
  "Thread"
  "Error"
  "Self"
] @type.builtin

[
  "="
  "+="
  "-="
  "*="
  "/="
  "%="
  "+"
  "-"
  "*"
  "**"
  "/"
  "%"
  "++"
  "--"
  "=="
  "!="
  "<"
  "<="
  ">"
  ">="
  "&&"
  "||"
  "!"
  "&"
  "."
  ".."
] @operator

[
  "("
  ")"
  "{"
  "}"
  "["
  "]"
] @punctuation.bracket

[
  ","
  ":"
] @punctuation.delimiter
