;;; Generated by scripts/build_syntax_highlighting.py
;;; Keep in sync with editor-support/spec/definitions.json

(comment) @comment
(line_comment) @comment
(block_comment) @comment
(string_literal) @string
(char_literal) @string.special
(int_literal) @number
(float_literal) @number.float

(identifier) @variable
(function_declaration name: (identifier) @function)
(call_expression function: (identifier) @function.call)
(type_identifier) @type

[
  "if"
  "else"
  "for"
  "while"
  "match"
  "break"
  "continue"
  "return"
  "in"
  "func"
  "class"
  "interface"
  "enum"
  "import"
  "const"
  "auto"
  "common"
  "returns"
  "is"
  "as"
] @keyword

[
  "true"
  "false"
  "none"
  "ok"
  "err"
] @constant.builtin

[
  "int"
  "float"
  "bool"
  "char"
  "string"
  "void"
  "optional"
  "result"
] @type.builtin

[
  "!="
  "::"
  "->"
  "+="
  "-="
  "/="
  "%="
  ">="
  "=="
  "&&"
  "||"
  "*="
  "<="
  "%"
  "="
  "."
  "/"
  "<"
  ">"
  "+"
  "*"
  "-"
  "!"
] @operator

[
  "("
  ")"
  "{"
  "}"
  "["
  "]"
] @punctuation.bracket

[
  ","
  ":"
] @punctuation.delimiter
