<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Mux</string>
	<key>scopeName</key>
	<string>source.mux</string>
	<key>fileTypes</key>
	<array>
		<string>mux</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#delimiters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.mux</string>
					<key>match</key>
					<string>//.*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.mux</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.mux</string>
					<key>match</key>
					<string>\b(if|else|for|while|match|break|continue)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.declaration.mux</string>
					<key>match</key>
					<string>\b(auto|func|returns|return|const|class|interface|enum|import)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.declaration.mux</string>
					<key>match</key>
					<string>\b(as|in|is)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.mux</string>
					<key>match</key>
					<string>\b(none|true|false|common)\b</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.mux</string>
					<key>match</key>
					<string>(&amp;=|\+=|-=|%=|\*=|/=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.mux</string>
					<key>match</key>
					<string>(\+\+)|(--)|(\*\*)|[+\-*/%]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.mux</string>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.mux</string>
					<key>match</key>
					<string>(&amp;&amp;|\|\|)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.mux</string>
					<key>match</key>
					<string>[!&amp;]|\.\.?|\.\.</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.mux</string>
					<key>match</key>
					<string>\b[-+]?[0-9][0-9_]*\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.mux</string>
					<key>match</key>
					<string>\b[-+]?([0-9][0-9_]*\.[0-9][0-9_]*|[0-9][0-9_]*\.)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.mux</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.mux</string>
							<key>match</key>
							<string>\\(n|r|t|0|\\|'|")</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.mux</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.mux</string>
							<key>match</key>
							<string>\\(n|r|t|0|\\|'|")</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.mux</string>
					<key>match</key>
					<string>\b_\b</string>
				</dict>
			</array>
		</dict>
		<key>delimiters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.mux</string>
					<key>match</key>
					<string>[(){}\[\],:]</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.mux</string>
					<key>match</key>
					<string>\b[a-zA-Z_][a-zA-Z0-9_]*\b</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
